/* Hand-maintained Host-for-Client Remote contribution (strict codecs).
 * Regenerated by typert when the package joins the workspace emit face. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SessionId } from '@deepseek-ai/dsh-session/types'
import type {
  BafWorkflowChangeRequest,
  BafWorkflowGateResolveRequest,
  BafWorkflowResumeRequest,
  BafWorkflowSessionRequest,
  BafWorkflowStartIntakeRequest,
  BafWorkflowTransitionRequest,
} from './index.ts'

/** Opaque tab view carried over the wire until generator-owned schemas land. */
type WorkflowTabViewWire = Readonly<Record<string, unknown>>

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$bafWorkflowView {
    getTabView: (request: BafWorkflowSessionRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
    startIntake: (request: BafWorkflowStartIntakeRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
    confirmIntake: (request: BafWorkflowChangeRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
    rejectIntake: (request: BafWorkflowChangeRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
    transition: (request: BafWorkflowTransitionRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
    resume: (request: BafWorkflowResumeRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
    gateResolve: (request: BafWorkflowGateResolveRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
  }
  interface TypertRemoteMap {
    'bafWorkflowView/getTabView': (request: BafWorkflowSessionRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
    'bafWorkflowView/startIntake': (request: BafWorkflowStartIntakeRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
    'bafWorkflowView/confirmIntake': (request: BafWorkflowChangeRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
    'bafWorkflowView/rejectIntake': (request: BafWorkflowChangeRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
    'bafWorkflowView/transition': (request: BafWorkflowTransitionRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
    'bafWorkflowView/resume': (request: BafWorkflowResumeRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
    'bafWorkflowView/gateResolve': (request: BafWorkflowGateResolveRequest) => Promise<RemoteResult<WorkflowTabViewWire>>
  }
  interface TypertRemoteNamespaceMap {
    bafWorkflowView: TypertRemoteNamespace$bafWorkflowView
  }
}

void 0 as SessionId

/**
 * Minimal schema accepted by Client Remote mount (`mode: 'strict'` + parse()).
 * @returns schema with parse().
 */
function opaqueSchema(): { parse: (value: unknown) => unknown } {
  return {
    parse(value: unknown): unknown {
      return value
    },
  }
}

const requestSchema = opaqueSchema()
const tabViewSchema = opaqueSchema()

/**
 * @param name - JSON parameter wire name.
 * @param typeSymbol - type identity for the strict codec.
 * @returns parameter descriptor.
 */
function jsonParam(name: string, typeSymbol: string) {
  return {
    name,
    wire: name,
    source: 'json' as const,
    codec: {
      mode: 'strict' as const,
      typeSymbol,
      schema: requestSchema,
    },
  }
}

/**
 * @param method - Remote method name.
 * @param requestSymbol - request type symbol.
 * @returns invocation descriptor.
 */
function remoteDescriptor(method: string, requestSymbol: string) {
  return {
    id: `@deepseek-ai/dsh-client-ui-baf-workflow#bafWorkflowView/${method}`,
    service: 'bafWorkflowView',
    namespace: 'bafWorkflowView',
    method,
    invocation: { kind: 'direct' as const },
    parameters: [jsonParam('request', requestSymbol)],
    result: {
      mode: 'strict' as const,
      typeSymbol: '@deepseek-ai/dsh-baf-core#WorkflowTabView',
      schema: tabViewSchema,
    },
    sourceLocation: { file: 'packages/client/ui-baf-workflow/src/index.ts', line: 1, column: 1 },
  }
}

/** Client Remote contribution for the BAF workflow Tab. */
export const TYPERT_REMOTE: TypertRemoteContribution = {
  package: '@deepseek-ai/dsh-client-ui-baf-workflow',
  descriptors: [
    remoteDescriptor('getTabView', '@deepseek-ai/dsh-client-ui-baf-workflow#BafWorkflowSessionRequest'),
    remoteDescriptor('startIntake', '@deepseek-ai/dsh-client-ui-baf-workflow#BafWorkflowStartIntakeRequest'),
    remoteDescriptor('confirmIntake', '@deepseek-ai/dsh-client-ui-baf-workflow#BafWorkflowChangeRequest'),
    remoteDescriptor('rejectIntake', '@deepseek-ai/dsh-client-ui-baf-workflow#BafWorkflowChangeRequest'),
    remoteDescriptor('transition', '@deepseek-ai/dsh-client-ui-baf-workflow#BafWorkflowTransitionRequest'),
    remoteDescriptor('resume', '@deepseek-ai/dsh-client-ui-baf-workflow#BafWorkflowResumeRequest'),
    remoteDescriptor('gateResolve', '@deepseek-ai/dsh-client-ui-baf-workflow#BafWorkflowGateResolveRequest'),
  ],
}

export default TYPERT_REMOTE
